import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { 
  Check, 
  ArrowRight, 
  ArrowLeft,
  Building2,
  Link as LinkIcon,
  CheckCircle2,
  Shield,
  Eye,
  Lock,
  Users,
  Settings,
  BarChart3,
  Share2,
  FileText,
  Sparkles
} from 'lucide-react';
import { BUSINESS_MODELS, STAGES } from '@/data/mockData';
import { toast } from 'sonner';

const EnhancedFounderOnboarding = () => {
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const totalSteps = 10;
  
  const [formData, setFormData] = useState({
    // Step 1: Invitation
    invitedBy: 'StartupTN',
    companyName: 'Your Startup',
    role: 'Founder Admin',
    
    // Step 2: Trust & Consent
    understoodDataSharing: false,
    reviewedVisibility: false,
    
    // Step 3: Company Details
    website: '',
    sector: '',
    stage: '',
    businessModel: '',
    hq: '',
    founders: '',
    contactEmail: '',
    reportingOwner: '',
    financeOwner: '',
    reportingCadence: 'monthly',
    
    // Step 4: Team Invites
    teamMembers: [],
    
    // Step 5: Data Sources
    connectedSources: [],
    
    // Step 6: Metric Mappings
    metricMappings: [
      { source: 'Stripe Revenue', mapped: 'Monthly Revenue', value: '$125K', confidence: 'high', approved: false },
      { source: 'Zoho Cash Account', mapped: 'Cash Balance', value: '$1.5M', confidence: 'high', approved: false },
      { source: 'Jira Completed', mapped: 'Sprint Completion', value: '85%', confidence: 'medium', approved: false },
      { source: 'HubSpot Pipeline', mapped: 'Pipeline Value', value: '$450K', confidence: 'high', approved: false }
    ],
    
    // Step 7: Sharing Preferences
    sharingPreferences: {
      revenue: { investors: true, internal: true, update: true, board: true, dashboard: true, needsApproval: false },
      jiraTickets: { investors: false, internal: true, update: true, board: false, dashboard: false, needsApproval: false },
      sprintDetails: { investors: false, internal: true, update: false, board: false, dashboard: false, needsApproval: false },
      risks: { investors: true, internal: true, update: true, board: true, dashboard: true, needsApproval: true }
    },
    
    // Step 9: Reporting
    reportDueDate: 5,
    reminderSchedule: '3_days',
    defaultRecipients: [],
    boardReportFreq: 'quarterly',
    autoGenerateDrafts: true
  });

  const progress = (step / totalSteps) * 100;

  const steps = [
    { num: 1, title: 'Accept Invitation', icon: CheckCircle2 },
    { num: 2, title: 'Trust & Data Sharing', icon: Shield },
    { num: 3, title: 'Company Details', icon: Building2 },
    { num: 4, title: 'Connect Data Sources', icon: LinkIcon },
    { num: 5, title: 'Review Metrics', icon: BarChart3 },
    { num: 6, title: 'Sharing Preferences', icon: Share2 },
    { num: 7, title: 'Invite Team', icon: Users },
    { num: 8, title: 'Dashboard Preview', icon: Eye },
    { num: 9, title: 'Reporting Setup', icon: FileText },
    { num: 10, title: 'Complete', icon: Sparkles }
  ];

  const integrationOptions = [
    { id: 'zoho', name: 'Zoho Books', type: 'accounting', required: true, time: '2 min' },
    { id: 'stripe', name: 'Stripe', type: 'payments', required: true, time: '2 min' },
    { id: 'hubspot', name: 'HubSpot', type: 'crm', required: false, time: '3 min' },
    { id: 'salesforce', name: 'Salesforce', type: 'crm', required: false, time: '3 min' },
    { id: 'jira', name: 'Jira', type: 'project', required: false, time: '2 min' },
    { id: 'github', name: 'GitHub', type: 'code', required: false, time: '2 min' }
  ];

  const handleNext = () => {
    // Validation
    if (step === 2 && (!formData.understoodDataSharing || !formData.reviewedVisibility)) {
      toast.error('Please review and accept data sharing terms');
      return;
    }
    
    if (step < totalSteps) {
      setStep(step + 1);
    } else {
      toast.success('Onboarding complete!', {
        description: 'Welcome to your Founder Workspace'
      });
      navigate('/founder');
    }
  };

  const handleBack = () => {
    if (step > 1) setStep(step - 1);
  };

  const handleConnectSource = (sourceId) => {
    setFormData(prev => ({
      ...prev,
      connectedSources: [...prev.connectedSources, sourceId]
    }));
    toast.success('Integration connected!');
  };

  const handleApproveMapping = (index) => {
    const newMappings = [...formData.metricMappings];
    newMappings[index].approved = !newMappings[index].approved;
    setFormData(prev => ({ ...prev, metricMappings: newMappings }));
  };

  return (
    <div className="min-h-screen bg-background p-4">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-12 w-12 rounded-lg bg-primary flex items-center justify-center">
              <span className="text-primary-foreground font-bold text-xl">S</span>
            </div>
            <div>
              <h1 className="text-2xl font-semibold">Founder Onboarding</h1>
              <p className="text-sm text-muted-foreground">Set up your workspace and start reporting</p>
            </div>
          </div>
          
          <div className="space-y-2">
            <div className="flex items-center justify-between text-sm">
              <span className="font-medium">Step {step} of {totalSteps}</span>
              <span className="text-muted-foreground">{Math.round(progress)}% complete</span>
            </div>
            <Progress value={progress} className="h-2" />
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Left Stepper */}
          <div className="lg:col-span-1">
            <Card>
              <CardContent className="p-4">
                <div className="space-y-2">
                  {steps.map((s) => {
                    const Icon = s.icon;
                    const isActive = s.num === step;
                    const isComplete = s.num < step;
                    
                    return (
                      <div
                        key={s.num}
                        className={`flex items-center gap-3 p-2 rounded-lg transition-colors ${
                          isActive ? 'bg-primary/10 border border-primary' :
                          isComplete ? 'bg-success/10' :
                          'bg-muted/50'
                        }`}
                      >
                        <div className={`shrink-0 h-7 w-7 rounded-full flex items-center justify-center ${
                          isActive ? 'bg-primary text-primary-foreground' :
                          isComplete ? 'bg-success text-success-foreground' :
                          'bg-muted text-muted-foreground'
                        }`}>
                          {isComplete ? (
                            <Check className="h-4 w-4" />
                          ) : (
                            <Icon className="h-4 w-4" />
                          )}
                        </div>
                        <p className={`text-xs font-medium ${
                          isActive ? 'text-foreground' : 'text-muted-foreground'
                        }`}>
                          {s.title}
                        </p>
                      </div>
                    );
                  })}\n                </div>
              </CardContent>
            </Card>

            {/* Helper Rail */}
            <Card className="mt-4">
              <CardContent className="p-4">
                <div className="space-y-2">
                  <h3 className="text-sm font-semibold flex items-center gap-2">
                    <Shield className="h-4 w-4 text-primary" />
                    Why this matters
                  </h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {step === 1 && "You've been invited to share operational data with your investors. This streamlines monthly reporting."}
                    {step === 2 && "Understanding what data is shared and who can see it builds trust and transparency."}
                    {step === 3 && "Accurate company details ensure proper reporting structure and stakeholder alignment."}
                    {step === 4 && "Connecting data sources once eliminates manual data entry every month."}
                    {step === 5 && "Validating metric mappings ensures investors see accurate, trustworthy numbers."}
                    {step === 6 && "You control what's visible to investors vs. what stays internal."}
                    {step === 7 && "Inviting your team enables collaborative reporting and data validation."}
                    {step === 8 && "Preview helps you see exactly what investors will see before going live."}
                    {step === 9 && "Configure reporting cadence and automation to save time monthly."}
                    {step === 10 && "You're all set! Your automated reporting workspace is ready."}
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-3">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  {React.createElement(steps[step - 1].icon, { className: "h-5 w-5" })}
                  {steps[step - 1].title}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Step 1: Accept Invitation */}
                {step === 1 && (
                  <div className="space-y-6">
                    <div className="text-center py-6">
                      <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 mb-4">
                        <CheckCircle2 className="h-8 w-8 text-primary" />
                      </div>
                      <h2 className="text-2xl font-semibold mb-2">You're Invited!</h2>
                      <p className="text-muted-foreground max-w-md mx-auto">
                        {formData.invitedBy} has invited you to join their portfolio monitoring platform
                      </p>
                    </div>
                    
                    <div className="max-w-md mx-auto space-y-4">
                      <div className="p-4 border rounded-lg">
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-sm text-muted-foreground">Invited by</span>
                          <Badge>{formData.invitedBy}</Badge>
                        </div>
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-sm text-muted-foreground">Company</span>
                          <span className="font-medium">{formData.companyName}</span>
                        </div>
                        <div className="flex items-center justify-between">
                          <span className="text-sm text-muted-foreground">Your Role</span>
                          <Badge variant="outline">{formData.role}</Badge>
                        </div>
                      </div>
                      
                      <div className="bg-muted/50 rounded-lg p-4 space-y-2">
                        <p className="text-sm font-medium">What you can do:</p>
                        <ul className="space-y-1 text-sm text-muted-foreground">
                          <li className="flex items-start gap-2">
                            <Check className="h-4 w-4 text-success shrink-0 mt-0.5" />
                            <span>Submit monthly investor updates automatically</span>
                          </li>
                          <li className="flex items-start gap-2">
                            <Check className="h-4 w-4 text-success shrink-0 mt-0.5" />
                            <span>Connect your tools for automated data sync</span>
                          </li>
                          <li className="flex items-start gap-2">
                            <Check className="h-4 w-4 text-success shrink-0 mt-0.5" />
                            <span>Control what data is shared with investors</span>
                          </li>
                          <li className="flex items-start gap-2">
                            <Check className="h-4 w-4 text-success shrink-0 mt-0.5" />
                            <span>Chat directly with investors and board members</span>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                )}

                {/* Step 2: Trust & Consent */}
                {step === 2 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Trust & Data Sharing</h3>
                      <p className="text-sm text-muted-foreground">
                        Understanding what data is shared and who can see it
                      </p>
                    </div>
                    
                    <div className="space-y-4">
                      <Card className="border-primary/30">
                        <CardHeader>
                          <CardTitle className="text-base">What Data Will Be Synced</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-3">
                          <div className="flex items-start gap-3">
                            <CheckCircle2 className="h-5 w-5 text-success shrink-0 mt-0.5" />
                            <div>
                              <p className="text-sm font-medium">Financial Metrics</p>
                              <p className="text-xs text-muted-foreground">Revenue, cash, burn rate from connected accounting tools</p>
                            </div>
                          </div>
                          <div className="flex items-start gap-3">
                            <CheckCircle2 className="h-5 w-5 text-success shrink-0 mt-0.5" />
                            <div>
                              <p className="text-sm font-medium">GTM Metrics</p>
                              <p className="text-xs text-muted-foreground">Pipeline, customers, growth from CRM</p>
                            </div>
                          </div>
                          <div className="flex items-start gap-3">
                            <Lock className="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
                            <div>
                              <p className="text-sm font-medium">Internal Notes</p>
                              <p className="text-xs text-muted-foreground">Your private notes remain private</p>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                      
                      <Card>
                        <CardHeader>
                          <CardTitle className="text-base">Who Can See What</CardTitle>
                        </CardHeader>
                        <CardContent>
                          <Table>
                            <TableHeader>
                              <TableRow>
                                <TableHead>Data Type</TableHead>
                                <TableHead>Investors</TableHead>
                                <TableHead>Your Team</TableHead>
                              </TableRow>
                            </TableHeader>
                            <TableBody>
                              <TableRow>
                                <TableCell>Financial Metrics</TableCell>
                                <TableCell><Check className="h-4 w-4 text-success" /></TableCell>
                                <TableCell><Check className="h-4 w-4 text-success" /></TableCell>
                              </TableRow>
                              <TableRow>
                                <TableCell>Sprint Details</TableCell>
                                <TableCell className="text-muted-foreground">Summary only</TableCell>
                                <TableCell><Check className="h-4 w-4 text-success" /></TableCell>
                              </TableRow>
                              <TableRow>
                                <TableCell>Internal Notes</TableCell>
                                <TableCell>-</TableCell>
                                <TableCell><Check className="h-4 w-4 text-success" /></TableCell>
                              </TableRow>
                            </TableBody>
                          </Table>
                        </CardContent>
                      </Card>
                      
                      <div className="space-y-3">
                        <div className="flex items-center space-x-2">
                          <Checkbox
                            id="understood"
                            checked={formData.understoodDataSharing}
                            onCheckedChange={(checked) => 
                              setFormData(prev => ({ ...prev, understoodDataSharing: checked }))
                            }
                          />
                          <Label htmlFor="understood" className="text-sm cursor-pointer">
                            I understand what data will be shared with investors
                          </Label>
                        </div>
                        
                        <div className="flex items-center space-x-2">
                          <Checkbox
                            id="reviewed"
                            checked={formData.reviewedVisibility}
                            onCheckedChange={(checked) => 
                              setFormData(prev => ({ ...prev, reviewedVisibility: checked }))
                            }
                          />
                          <Label htmlFor="reviewed" className="text-sm cursor-pointer">
                            I have reviewed the visibility settings
                          </Label>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {/* Step 3: Company Details */}
                {step === 3 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Confirm Company Details</h3>
                      <p className="text-sm text-muted-foreground">
                        Verify and complete your company information
                      </p>
                    </div>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div>
                        <Label htmlFor="website">Website</Label>
                        <Input
                          id="website"
                          type="url"
                          placeholder="https://yourcompany.com"
                          value={formData.website}
                          onChange={(e) => setFormData(prev => ({ ...prev, website: e.target.value }))}
                          className="mt-2"
                        />
                      </div>
                      
                      <div>
                        <Label htmlFor="sector">Sector</Label>
                        <Input
                          id="sector"
                          placeholder="e.g., FinTech"
                          value={formData.sector}
                          onChange={(e) => setFormData(prev => ({ ...prev, sector: e.target.value }))}
                          className="mt-2"
                        />
                      </div>
                      
                      <div>
                        <Label>Stage</Label>
                        <Select value={formData.stage} onValueChange={(v) => setFormData(prev => ({ ...prev, stage: v }))}>
                          <SelectTrigger className="mt-2">
                            <SelectValue placeholder="Select stage" />
                          </SelectTrigger>
                          <SelectContent>
                            {STAGES.map(stage => (
                              <SelectItem key={stage} value={stage}>{stage}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <div>
                        <Label>Business Model</Label>
                        <Select value={formData.businessModel} onValueChange={(v) => setFormData(prev => ({ ...prev, businessModel: v }))}>
                          <SelectTrigger className="mt-2">
                            <SelectValue placeholder="Select model" />
                          </SelectTrigger>
                          <SelectContent>
                            {BUSINESS_MODELS.map(model => (
                              <SelectItem key={model} value={model}>{model}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <div>
                        <Label htmlFor="reportingOwner">Reporting Owner</Label>
                        <Input
                          id="reportingOwner"
                          placeholder="Name"
                          value={formData.reportingOwner}
                          onChange={(e) => setFormData(prev => ({ ...prev, reportingOwner: e.target.value }))}
                          className="mt-2"
                        />
                      </div>
                      
                      <div>
                        <Label>Reporting Cadence</Label>
                        <Select value={formData.reportingCadence} onValueChange={(v) => setFormData(prev => ({ ...prev, reportingCadence: v }))}>
                          <SelectTrigger className="mt-2">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="monthly">Monthly</SelectItem>
                            <SelectItem value="quarterly">Quarterly</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                  </div>
                )}

                {/* Step 4: Connect Data Sources */}
                {step === 4 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Connect Your Tools</h3>
                      <p className="text-sm text-muted-foreground">
                        Connect once, automate forever. No more manual data entry.
                      </p>
                    </div>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {integrationOptions.map(integration => {
                        const isConnected = formData.connectedSources.includes(integration.id);
                        return (
                          <Card key={integration.id} className={isConnected ? 'border-success' : ''}>
                            <CardContent className="p-4">
                              <div className="flex items-start justify-between mb-3">
                                <div>
                                  <p className="font-medium">{integration.name}</p>
                                  <p className="text-xs text-muted-foreground capitalize">{integration.type}</p>
                                </div>
                                {integration.required && (
                                  <Badge variant="outline" className="text-xs">Required</Badge>
                                )}
                              </div>
                              
                              <p className="text-xs text-muted-foreground mb-3">
                                Setup time: {integration.time}
                              </p>
                              
                              <Button
                                variant={isConnected ? 'outline' : 'default'}
                                size="sm"
                                className="w-full"
                                onClick={() => !isConnected && handleConnectSource(integration.id)}
                                disabled={isConnected}
                              >
                                {isConnected ? (
                                  <><CheckCircle2 className="h-4 w-4 mr-2" /> Connected</>
                                ) : (
                                  <><LinkIcon className="h-4 w-4 mr-2" /> Connect</>
                                )}
                              </Button>
                            </CardContent>
                          </Card>
                        );
                      })}
                    </div>
                  </div>
                )}

                {/* Step 5: Review Metrics */}
                {step === 5 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Review Detected Metrics</h3>
                      <p className="text-sm text-muted-foreground">
                        Validate that the mapped metrics are correct
                      </p>
                    </div>
                    
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Source Metric</TableHead>
                          <TableHead>Mapped To</TableHead>
                          <TableHead>Latest Value</TableHead>
                          <TableHead>Confidence</TableHead>
                          <TableHead className="text-center">Approve</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {formData.metricMappings.map((mapping, idx) => (
                          <TableRow key={idx}>
                            <TableCell className="font-medium">{mapping.source}</TableCell>
                            <TableCell>{mapping.mapped}</TableCell>
                            <TableCell className="font-mono">{mapping.value}</TableCell>
                            <TableCell>
                              <Badge variant={mapping.confidence === 'high' ? 'default' : 'outline'}>
                                {mapping.confidence}
                              </Badge>
                            </TableCell>
                            <TableCell className="text-center">
                              <Checkbox
                                checked={mapping.approved}
                                onCheckedChange={() => handleApproveMapping(idx)}
                              />
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                )}

                {/* Step 6: Sharing Preferences */}
                {step === 6 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Control What's Shared</h3>
                      <p className="text-sm text-muted-foreground">
                        Decide what metrics are visible to investors vs. what stays internal
                      </p>
                    </div>
                    
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Metric</TableHead>
                          <TableHead className="text-center">Investors</TableHead>
                          <TableHead className="text-center">Internal</TableHead>
                          <TableHead className="text-center">Updates</TableHead>
                          <TableHead className="text-center">Board</TableHead>
                          <TableHead className="text-center">Dashboard</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {Object.entries(formData.sharingPreferences).map(([key, prefs]) => (
                          <TableRow key={key}>
                            <TableCell className="font-medium capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</TableCell>
                            <TableCell className="text-center">
                              <Switch
                                checked={prefs.investors}
                                onCheckedChange={(checked) => 
                                  setFormData(prev => ({
                                    ...prev,
                                    sharingPreferences: {
                                      ...prev.sharingPreferences,
                                      [key]: { ...prefs, investors: checked }
                                    }
                                  }))
                                }
                              />
                            </TableCell>
                            <TableCell className="text-center">
                              <Switch
                                checked={prefs.internal}
                                onCheckedChange={(checked) => 
                                  setFormData(prev => ({
                                    ...prev,
                                    sharingPreferences: {
                                      ...prev.sharingPreferences,
                                      [key]: { ...prefs, internal: checked }
                                    }
                                  }))
                                }
                              />
                            </TableCell>
                            <TableCell className="text-center">
                              <Switch
                                checked={prefs.update}
                                onCheckedChange={(checked) => 
                                  setFormData(prev => ({
                                    ...prev,
                                    sharingPreferences: {
                                      ...prev.sharingPreferences,
                                      [key]: { ...prefs, update: checked }
                                    }
                                  }))
                                }
                              />
                            </TableCell>
                            <TableCell className="text-center">
                              <Switch
                                checked={prefs.board}
                                onCheckedChange={(checked) => 
                                  setFormData(prev => ({
                                    ...prev,
                                    sharingPreferences: {
                                      ...prev.sharingPreferences,
                                      [key]: { ...prefs, board: checked }
                                    }
                                  }))
                                }
                              />
                            </TableCell>
                            <TableCell className="text-center">
                              <Switch
                                checked={prefs.dashboard}
                                onCheckedChange={(checked) => 
                                  setFormData(prev => ({
                                    ...prev,
                                    sharingPreferences: {
                                      ...prev.sharingPreferences,
                                      [key]: { ...prefs, dashboard: checked }
                                    }
                                  }))
                                }
                              />
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                )}

                {/* Step 7: Invite Team */}
                {step === 7 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Invite Your Team</h3>
                      <p className="text-sm text-muted-foreground">
                        Collaborate with team members on reporting and data validation
                      </p>
                    </div>
                    
                    <div className="space-y-4">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <Label htmlFor="teamEmail">Email Address</Label>
                          <Input
                            id="teamEmail"
                            type="email"
                            placeholder="colleague@company.com"
                            className="mt-2"
                          />
                        </div>
                        <div>
                          <Label htmlFor="teamRole">Role</Label>
                          <Select>
                            <SelectTrigger className="mt-2" id="teamRole">
                              <SelectValue placeholder="Select role" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="admin">Admin</SelectItem>
                              <SelectItem value="editor">Editor</SelectItem>
                              <SelectItem value="viewer">Viewer</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                      
                      <Button variant="outline" className="w-full">
                        <Users className="h-4 w-4 mr-2" />
                        Add Team Member
                      </Button>
                      
                      {formData.teamMembers.length > 0 ? (
                        <Card>
                          <CardContent className="p-4">
                            <p className="text-sm text-muted-foreground">
                              {formData.teamMembers.length} team member(s) invited
                            </p>
                          </CardContent>
                        </Card>
                      ) : (
                        <p className="text-sm text-muted-foreground text-center py-4">
                          You can invite team members later from your workspace
                        </p>
                      )}
                    </div>
                  </div>
                )}

                {/* Step 8: Dashboard Preview */}
                {step === 8 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Dashboard Preview</h3>
                      <p className="text-sm text-muted-foreground">
                        Here's what investors will see on your company dashboard
                      </p>
                    </div>
                    
                    <div className="border rounded-lg p-6 bg-muted/20">
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                        <Card>
                          <CardContent className="p-4">
                            <p className="text-xs text-muted-foreground mb-1">Monthly Revenue</p>
                            <p className="text-2xl font-bold">$125K</p>
                            <p className="text-xs text-success">↑ 23% MoM</p>
                          </CardContent>
                        </Card>
                        <Card>
                          <CardContent className="p-4">
                            <p className="text-xs text-muted-foreground mb-1">Cash Balance</p>
                            <p className="text-2xl font-bold">$1.5M</p>
                            <p className="text-xs text-muted-foreground">15 months runway</p>
                          </CardContent>
                        </Card>
                        <Card>
                          <CardContent className="p-4">
                            <p className="text-xs text-muted-foreground mb-1">Pipeline Value</p>
                            <p className="text-2xl font-bold">$450K</p>
                            <p className="text-xs text-success">↑ 12% WoW</p>
                          </CardContent>
                        </Card>
                      </div>
                      
                      <div className="flex items-center justify-center gap-2 text-sm text-muted-foreground">
                        <Eye className="h-4 w-4" />
                        <span>Live data from your connected sources</span>
                      </div>
                    </div>
                    
                    <div className="bg-primary/10 rounded-lg p-4 flex items-start gap-3">
                      <Shield className="h-5 w-5 text-primary shrink-0 mt-0.5" />
                      <div className="space-y-1">
                        <p className="text-sm font-medium">Your data is secure</p>
                        <p className="text-xs text-muted-foreground">
                          Only metrics you've approved are visible. You can change visibility settings anytime.
                        </p>
                      </div>
                    </div>
                  </div>
                )}

                {/* Step 9: Reporting Setup */}
                {step === 9 && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-semibold mb-2">Reporting Schedule</h3>
                      <p className="text-sm text-muted-foreground">
                        Configure when and how reports are generated
                      </p>
                    </div>
                    
                    <div className="space-y-4">
                      <div>
                        <Label htmlFor="reportDueDate">Monthly Report Due Date</Label>
                        <Select 
                          value={String(formData.reportDueDate)} 
                          onValueChange={(v) => setFormData(prev => ({ ...prev, reportDueDate: parseInt(v) }))}
                        >
                          <SelectTrigger className="mt-2" id="reportDueDate">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {[1, 5, 10, 15, 20].map(day => (
                              <SelectItem key={day} value={String(day)}>
                                Day {day} of each month
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <div>
                        <Label htmlFor="reminderSchedule">Reminder Schedule</Label>
                        <Select 
                          value={formData.reminderSchedule} 
                          onValueChange={(v) => setFormData(prev => ({ ...prev, reminderSchedule: v }))}
                        >
                          <SelectTrigger className="mt-2" id="reminderSchedule">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="1_day">1 day before</SelectItem>
                            <SelectItem value="3_days">3 days before</SelectItem>
                            <SelectItem value="1_week">1 week before</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <div>
                        <Label htmlFor="boardReportFreq">Board Report Frequency</Label>
                        <Select 
                          value={formData.boardReportFreq} 
                          onValueChange={(v) => setFormData(prev => ({ ...prev, boardReportFreq: v }))}
                        >
                          <SelectTrigger className="mt-2" id="boardReportFreq">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="monthly">Monthly</SelectItem>
                            <SelectItem value="quarterly">Quarterly</SelectItem>
                            <SelectItem value="custom">Custom</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <div className="flex items-center justify-between p-4 border rounded-lg">
                        <div>
                          <p className="text-sm font-medium">Auto-generate draft reports</p>
                          <p className="text-xs text-muted-foreground">
                            We'll create a draft based on your metrics for you to review
                          </p>
                        </div>
                        <Switch
                          checked={formData.autoGenerateDrafts}
                          onCheckedChange={(checked) => 
                            setFormData(prev => ({ ...prev, autoGenerateDrafts: checked }))
                          }
                        />
                      </div>
                    </div>
                  </div>
                )}

                {/* Step 10: Complete */}
                {step === 10 && (
                  <div className="space-y-6 py-6">
                    <div className="text-center space-y-3">
                      <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-success/10 mb-4">
                        <Sparkles className="h-8 w-8 text-success" />
                      </div>
                      <h2 className="text-2xl font-semibold">Setup Complete! 🎉</h2>
                      <p className="text-muted-foreground max-w-md mx-auto">
                        Your Founder Workspace is ready. Start exploring your dashboard and let us handle the reporting.
                      </p>
                    </div>
                    
                    <Card className="bg-muted/50">
                      <CardContent className="p-6 space-y-4">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Building2 className="h-5 w-5 text-muted-foreground" />
                            <span className="font-medium">Company</span>
                          </div>
                          <span className="text-sm">{formData.companyName}</span>
                        </div>
                        
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <LinkIcon className="h-5 w-5 text-muted-foreground" />
                            <span className="font-medium">Connected Sources</span>
                          </div>
                          <span className="text-sm">{formData.connectedSources.length} active</span>
                        </div>
                        
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <BarChart3 className="h-5 w-5 text-muted-foreground" />
                            <span className="font-medium">Metrics Mapped</span>
                          </div>
                          <span className="text-sm">{formData.metricMappings.length} approved</span>
                        </div>
                        
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <FileText className="h-5 w-5 text-muted-foreground" />
                            <span className="font-medium">Reporting</span>
                          </div>
                          <span className="text-sm capitalize">{formData.reportingCadence}</span>
                        </div>
                      </CardContent>
                    </Card>
                    
                    <div className="bg-primary/10 rounded-lg p-4">
                      <p className="text-sm font-medium mb-2">What happens next?</p>
                      <ul className="space-y-1 text-sm text-muted-foreground">
                        <li className="flex items-start gap-2">
                          <Check className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                          <span>We'll sync your data from connected sources</span>
                        </li>
                        <li className="flex items-start gap-2">
                          <Check className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                          <span>Auto-generate your first draft report before the due date</span>
                        </li>
                        <li className="flex items-start gap-2">
                          <Check className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                          <span>Send you a reminder {formData.reminderSchedule.replace('_', ' ')}</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                )}

                {/* Navigation */}
                <div className="flex items-center justify-between pt-6 border-t">
                  <Button
                    variant="outline"
                    onClick={handleBack}
                    disabled={step === 1}
                  >
                    <ArrowLeft className="h-4 w-4 mr-2" />
                    Back
                  </Button>
                  
                  <Button onClick={handleNext}>
                    {step === totalSteps ? (
                      <>Complete Setup<CheckCircle2 className="h-4 w-4 ml-2" /></>
                    ) : (
                      <>Continue<ArrowRight className="h-4 w-4 ml-2" /></>
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EnhancedFounderOnboarding;
